### ISSUE TITLE
TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by jsillitoe** [assister-ai/koa-neo4j-starter-kit#1]
Following the install and usage instructions in the readme.

After `npm start` I get the following error:

```
App listening on port 3000.
Error connecting to the Neo4j instance, check connection options
TypeError: Cannot read property 'parse' of undefined
    at /home/jrs1/neo4j/playing/koa-neo4j-starter-kit/node_modules/koa-neo4j/index.js:2722:72
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:18618) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'parse' of undefined
(node:18618) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 2bigO** [comment]
@jsillitoe this was due to an old version of koa-neo4j in `package.json`. I reproduced the issue and bd6a844 did fix it. Pull now, `npm install` and you should be fine. Feel free to re-open if the issue persisted.

**Comment by 2bigO** [comment]
@jsillitoe 
FYI, I've revamped the docs at https://github.com/assister-ai/koa-neo4j, updated the master branch of the starter kit with ES6 and babel, and moved the version you were using to [node-4 branch](https://github.com/assister-ai/koa-neo4j-starter-kit/tree/node-4)
