### ISSUE TITLE
space in route

### ISSUE THREAD

**Issue by rogueturnip** [assister-ai/koa-neo4j-starter-kit#2]
Hi!

First, great module, works very well.

I've run into one thing and I've tried a number of things but can't seem to get through it.  I'm doing a query on a user name in neo4j and the name contains a space.  This gets turned into %20 in the url but it doesn't seem to get turned back to a space.

I just want to validate that this is as expected, the route does not parse out the % values to actual characters to pass into the cypher query.  If that's the case, any suggestions as I don't want to recreate the data set to remove all spaces in all properties.

Thanks!

**Comment by 2bigO** [comment]
Hi @rogueturnip 

Could you please provide a more concrete example including some code? Are you facing this on a GET request with url params?

**Comment by rogueturnip** [comment]
Sure, thanks for following up.  What I'm trying to is look for a user node by name so I created:
app.defineApi({
  method: 'GET',
  route: '/users/:name',
  cyperQueryFile: '.src/users/name.cyp'
})

Then I try to query like this
get /users/John%20Smith

I don't believe the %20 is being changed back to a space and I'm not having my Cypher query work.  It works when I use the Neo4j browser and enter in "John Smith"

Thanks!

**Comment by 2bigO** [comment]
I just tested this on the starter kit and it seems to be working, see below:

# ./src/article/index.js
```js
app.defineAPI({
    method: 'GET',
    route: '/articles/:skip/:john',
    preProcess: logValues,
    cypherQueryFile: './src/article/articles.cyp'
});
```

Note the usage of [`logValues`](https://github.com/assister-ai/koa-neo4j-starter-kit/blob/master/src/article/index.js#L4) as `preProcess`, this helps with seeing the values passed to the endpoint in console.

```js
import {logValues} from 'koa-neo4j/debug';
```

# ./src/article/articles.cyp

```cypher
RETURN $john
```

# Result

<img width="300" alt="john1" src="https://user-images.githubusercontent.com/1758649/31578435-06c57866-b12e-11e7-95e4-5ef418dd7661.png">

<img width="300" alt="john1" src="https://user-images.githubusercontent.com/1758649/31578444-380f2840-b12e-11e7-879b-d1fae74a16f9.png">

I suggest that you use `logValues` as per this example and investigate further what is actually happening.

**Comment by rogueturnip** [comment]
Thanks!  I'll check this out!

**Comment by 2bigO** [comment]
@rogueturnip has this issue been resolved?

**Comment by rogueturnip** [comment]
Yes it has, thanks, I'll close the issue.
